services:
  db-dev:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
    ports:
      -  "3307:3306"
  db-prod:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: prod_password
    ports:
      -  "3308:3306"
    volumes:
      - prod_data:/var/lib/mysql
volumes:
  dev_data:
  prod_data: